name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_PUSH_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PUSH_SECRET }} 
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: docker build
      run: |
        docker build --file Dockerfile -t scheibling/py-dnslogserver:1.0-alpine . && |
        docker tag scheibling/py-dnslogserver:1.0-alpine scheibling/py-dnslogserver:latest && |
        docker tag scheibling/py-dnslogserver:1.0-alpine scheibling/py-dnslogserver:latest-alpine

    - name: docker push
      run: |
        docker push scheibling/py-dnslogserver:latest && |
        docker push scheibling/py-dnslogserver:latest-alpine && |
        docker push scheibling/py-dnslogserver:1.0-alpine