name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_PUSH_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PUSH_SECRET }} 
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: docker build
      env:
        DOCKER_REPO: ${{ env.GITHUB_REPOSITORY }}
      run: |
        docker build --file Dockerfile -t $DOCKER_REPO:latest .

    - name: docker push
      env:
        DOCKER_REPO: ${{ env.GITHUB_REPOSITORY }}
      run: |
        docker push ${DOCKER_REPO}:latest